language: ruby

rvm:
  - 2.4.1

before_script:
 - mkdir ~/.task
 - echo data.location=~/.task > ~/.taskrc

before_install:
 - echo | sudo add-apt-repository ppa:ultrafredde/ppa
 - sudo apt-get update
 - sudo apt-get install task
